sonar.projectKey=frontend-rc
sonar.projectName=Frontend-RC
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/.angular/**,**/dist/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=sqp_8cd1e87a97a0c137b33ec90549b950e4c1cb3544